spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer2 #服务器上配置主机名叫peer2
  client:
    service-url:
      defaultZone: http://peer3:1113/eureka/,http://peer1:1111/eureka/

server:
  port: 1112
