spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer3 #服务器上配置主机名叫peer3
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/

server:
  port: 1113
